---
title: "Diffusion Feasibility Space Analysis"
author: "Rudolph Santarromana"
date: "2024-01-26"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(triangle)
library(stats)
library(Hmisc)
```

## R Markdown

```{r Distribution of three parameters}

#draw from a trunctated triangular distribution
rtrianglet <- function(n = 1, a, b, c, t.a = NULL, t.b = NULL) {
  # #expected value and variance of a triangular distribution
  # mu <- (a + b + c)/3
  # sigma <- 1/18(a^2 + b^2 + c^2 - a*b - a*c - b*c)
  
  if(is.null(t.a)) F.a <- ptriangle(a, a, b, c) else F.a <- ptriangle(t.a, a, b, c) #lower trunctation
  if(is.null(t.b)) F.b <- ptriangle(b, a, b, c) else F.b <- ptriangle(t.b, a, b, c) #upper trunctation
  
  u <- runif(n, min = F.a, max = F.b)
  draw <- qtriangle(u, a, b, c)
  return(draw)
}

#takes n draws from a trunctated triangular distrubtion
Initial.cap <- function(n = 1, pct = 0.2, operating = 67, construction = 12.484, proposed = 111.411) { 
  # operating <- 64.3 #GW. according to GWEC global offshore wind report 2023
  # under.construction <- 12.484 #GW. According to wikipedia
  # proposed <- 111.411 #GW. According to wikipedia
  
  min <- 0 #min of dist.
  max <- operating + construction + proposed #max of dist
  mode <- operating + pct*construction #assume a likely number is that 20% of capacity under construction will be completed. mode of dist
  
  draw <- rtrianglet(n = n, a = min, b = max, c = mode, t.a = operating)
  return(draw) 
} #output in GW

Growth.rate <- function(n = 1, min = 0.02, max = 0.36, mode = 0.3) {
  draw <- rtrianglet(n = n, a = 0, b = 1, c = mode, t.a = min, t.b = max)
  return(draw)
} #output in %/year

Demand.pull <- function(year, anticipation = 5) { #input is actual year, i.e. "2025"
  #from GWEC offshore wind report 2023
  operating <- 67
  pipeline.2033 <- operating + 380 #GW added
  target.2030 <- 500 #GW. According to IRENA 1.5C compliant scenario
  target.2050 <- 2500 #GW. According to IRENA 1.5C compliant Scenario
  
  x <- c(2030, 2050)
  y <- c(target.2030, target.2050)
  
  #apply demand anticipation 
  year <- year + anticipation
  
  if(year < min(x) | year > max(x)) point <- Hmisc::approxExtrap(x,y,xout = year)$y else point <- approx(x, y , xout = year)$y
  
  if(point < target.2030) return(target.2030)
  else if(point > target.2050) return(target.2050)
  else return(point)
}

```

```{r Complete one run}
Adoption.curve <- function(years = seq(2024, 2050)) {
  #draw initial parameters
  init.cap <- Initial.cap()
  growth.r <- Growth.rate()
  pull.v <- c()
  cap.v <- c()
  
  # Results.DF <- data.frame(Years = years)
  for(y in years) {
    if(y == 2024) {
      this.cap <- init.cap
      pull.v <- c(Demand.pull(y))
      cap.v <- c(this.cap)
    } else {
      last.cap <- tail(cap.v,1) #last value in the capacity vector is the last year's capacity
      pull <- Demand.pull(y) #take the demand pull value for that year
      pull.v <- c(pull.v, pull)
      this.cap <- last.cap + growth.r*last.cap*(1-(last.cap/pull))
      cap.v <- c(cap.v, this.cap)
    }
    
  } 
  Result.DF <- data.frame(Year = years, Pull = pull.v, Capacity = cap.v)
  return(Result.DF)
}

```

```{r N runs}
Monte.Carlo <- function(N = 100) {
  Result <- Adoption.curve() #first run
  # rownames(Result) <- 2024:2050
  for(n in 2:N) {
    this.run <- Adoption.curve()$Capacity
    Result <- cbind(Result, run = this.run)
  }
  colnames(Result) <- c("Year","Pull",seq(1:N))
  return(Result)
}

All.Runs <- Monte.Carlo(1000)

#Create a summary of runs data.frame
All.Runs.Summary <- All.Runs[ , 1:2]
All.Runs.Summary$LOW.10 <- NA
All.Runs.Summary$IQR.25 <- NA
All.Runs.Summary$MED <- NA
All.Runs.Summary$IQR.75 <- NA
All.Runs.Summary$UPP.90 <- NA

for(y in 1:nrow(All.Runs)){
  year.v <- as.numeric(All.Runs[y, 3:ncol(All.Runs)])
  year.10 <- quantile(year.v, probs = 0.1)
  year.25 <- as.numeric(summary(year.v)["1st Qu."])
  year.50 <- as.numeric(summary(year.v)["Median"])
  year.75 <- as.numeric(summary(year.v)["3rd Qu."])
  year.90 <- quantile(year.v, probs = 0.9)
  
  All.Runs.Summary[y, "LOW.10"] <- year.10
  All.Runs.Summary[y, "IQR.25"] <- year.25
  All.Runs.Summary[y, "MED"] <- year.50
  All.Runs.Summary[y, "IQR.75"] <- year.75
  All.Runs.Summary[y, "UPP.90"] <- year.90
}

```


```{r VISUALIZE: Plot the figure}
plot(x = All.Runs$Year, y = All.Runs$Pull, lty = 2, lwd = 2, pch = 19, type = 'n', 
     xlim = c(2024, 2050), ylim = c(0, 3000), las = 1, xaxs = 'i', yaxs = 'i',
     xlab = "Year", ylab = "Global Capacity [GW]")
points(x = 2030, y = 380 + 67, cex = 2, lwd = 3)
points(x = 2030, y = 500, cex = 2, lwd = 3, col = 'green')
points(x = 2050, y = 2500, cex = 2, lwd = 3, col = 'green')
for(col in 3:ncol(All.Runs)){
  lines(x = All.Runs$Year, y = All.Runs[ ,col], col = rgb(0,0,1,0.01), lwd = 2)
}
lines(x = All.Runs.Summary$Year, y = All.Runs.Summary[ , "LOW.10"], col = 'red', lwd = 2)
lines(x = All.Runs.Summary$Year, y = All.Runs.Summary[ , "MED"], col = 'darkred', lwd = 2)
lines(x = All.Runs.Summary$Year, y = All.Runs.Summary[ , "UPP.90"], col = 'red', lwd = 2)

# #projections
# #IRENA Projections REmap CASE (IRENA, 2019)
# points(x = c(2030, 2050), y = c(228,1000), pch = 15, cex = 1.3,col ='blue') #IRENA Projections for overall OSW (IRENA, 2019)
# 
# #IEA Projections Sustainable Development Scenario (IEA, 2019): Offshore Wind Outlook 2019
# IEA.years <- c(2025,2030,2035,2040)
# IEA.SDS.cumul <- c(101,225,385,562) #[GW]
# IEA.SP.cumul <- c(77,165,262,342)
# 
# points(x = IEA.years, y = IEA.SDS.cumul, pch = 19,cex = 1.1,col = 'green')
# points(x = IEA.years, y = IEA.SP.cumul, pch = 18,col = 'orange')
# # curve(23*(1.157^(x - 2020)),from = 2018, to = 2040,lty = 2, col = 'green', add = TRUE) #SDS CAGR = 15.7 (2018 - 2040)
# # curve(23*(1.132^(x - 2020)),from = 2018, to = 2040,lty = 2, col = 'blue', add = TRUE) #SP CAGR = 13.2 (2018 to 2040)
# 
# #IEA Offshore Wind Outlook Report (IEA, 2019)
# # curve(exist.osw*(1.13)^(x - 2020), from = 2020, to = 2040, add = TRUE, col = 'orange', lty = 2)
# 
# #GWEC Global Offshore Wind Report (GWEC, 2020)
# GWEC.cumul <- c(35.6,45.3,54.4,64.3,77.3,98.8,120.3,145.8,172,203,234.9)
# GWEC.years <- seq(from = 2020, to = 2030, by = 1)
# points(x = GWEC.years, y = GWEC.cumul, col = 'red', pch = 19)
# 
# #BNEF (BNEF, 2018) 
# points(x = c(2030,2030), y = c(114.9,154), pch = c(17,18), col = 'purple')
# 
# #4C Offshore (2018)
# points(x = 2030, y = 193, pch = 20, col = 'yellow')
# 
# #Fortune Business Insights (Fortune Business Insights, 2019)
# points(x = 2026, y = 94.24, pch = 19, col = 'black')
```

